/**
 * YouTube content script — auto-injected on YouTube watch pages via manifest.json.
 *
 * Two-tier transcript extraction:
 *   Tier 1: Fetch timedtext XML via player API (fast, millisecond timestamps, silent)
 *   Tier 2: DOM scraping via transcript panel (reliable fallback, silent execution)
 *
 * Both tiers are fully silent — the user never sees UI flicker.
 */

import {
  extractVideoId,
  extractCaptionTracks,
  extractVideoMetadata,
  extractChapters,
  parseXMLCaptions,
} from '@/extractors/youtube-extractor';
import type { VideoContent, TranscriptSegment, Chapter } from '@/types';

// ---------------------------------------------------------------------------
// State
// ---------------------------------------------------------------------------

let cachedContent: VideoContent | null = null;
let cachedUrl = '';

// ---------------------------------------------------------------------------
// 1. Extract ytInitialPlayerResponse from page HTML
// ---------------------------------------------------------------------------

function extractPlayerResponseFromPage(): any {
  try {
    const scripts = document.querySelectorAll('script');
    for (const script of scripts) {
      const text = script.textContent || '';
      if (!text.includes('ytInitialPlayerResponse')) continue;

      const idx = text.indexOf('ytInitialPlayerResponse');
      const afterName = text.indexOf('=', idx);
      if (afterName === -1) continue;

      const jsonStart = text.indexOf('{', afterName);
      if (jsonStart === -1) continue;

      let depth = 0;
      let jsonEnd = -1;
      for (let i = jsonStart; i < text.length; i++) {
        if (text[i] === '{') depth++;
        else if (text[i] === '}') depth--;
        if (depth === 0) { jsonEnd = i + 1; break; }
      }
      if (jsonEnd === -1) continue;

      return JSON.parse(text.substring(jsonStart, jsonEnd));
    }
    return null;
  } catch (e) {
    console.error('[VideoLM] Failed to parse ytInitialPlayerResponse', e);
    return null;
  }
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function sleep(ms: number): Promise<void> {
  return new Promise((r) => setTimeout(r, ms));
}

function waitForElement(selector: string, timeout = 5000): Promise<Element | null> {
  return new Promise((resolve) => {
    const el = document.querySelector(selector);
    if (el) { resolve(el); return; }

    const obs = new MutationObserver(() => {
      const found = document.querySelector(selector);
      if (found) { obs.disconnect(); resolve(found); }
    });
    obs.observe(document.body, { childList: true, subtree: true });
    setTimeout(() => { obs.disconnect(); resolve(null); }, timeout);
  });
}

// ---------------------------------------------------------------------------
// 2. TIER 1: Fetch timedtext XML via player API (silent, millisecond precision)
// ---------------------------------------------------------------------------

/**
 * Attempt to fetch caption XML directly from the timedtext URL.
 * This uses the #movie_player element's getPlayerResponse() for a fresh URL,
 * then fetches via the page's context (has cookies + origin).
 *
 * Returns segments if successful, empty array if POT token blocks the request.
 */
async function extractTranscriptTier1(playerResponse: any): Promise<TranscriptSegment[]> {
  try {
    const tracks = extractCaptionTracks(playerResponse);
    if (tracks.length === 0) return [];

    // Prefer manual captions over auto-generated
    const bestTrack = tracks.find((t) => !t.isAutoGenerated) ?? tracks[0];
    if (!bestTrack.baseUrl) return [];

    // Try fetching caption XML — may fail due to POT token requirement
    const resp = await fetch(bestTrack.baseUrl, { credentials: 'include' });
    if (!resp.ok) return [];

    const xml = await resp.text();
    if (!xml || xml.length < 10) return []; // Empty response = POT blocked

    return parseXMLCaptions(xml);
  } catch {
    return [];
  }
}

// ---------------------------------------------------------------------------
// 3. TIER 2: Silent DOM scraping (reliable fallback)
// ---------------------------------------------------------------------------

/**
 * Extract transcript by programmatically opening the transcript panel,
 * reading DOM segments, then closing the panel.
 *
 * Optimized for silent execution:
 * - Description expand happens instantly (no animation wait)
 * - Panel is opened, read, and closed within ~2 seconds
 * - If panel was already open, just reads and leaves it open
 * - If panel cannot be opened, returns empty (no error UI)
 */
async function extractTranscriptTier2(): Promise<TranscriptSegment[]> {
  try {
    // Check if transcript panel is already open
    const existingSegments = document.querySelectorAll('ytd-transcript-segment-renderer');
    if (existingSegments.length > 0) {
      return readTranscriptSegmentsFromDOM();
    }

    // Step 1: Expand description silently (needed to access transcript button)
    const expandBtn = document.querySelector('#expand') as HTMLElement;
    if (expandBtn) {
      expandBtn.click();
      await sleep(300);
    }

    // Step 2: Find and click the transcript button
    const transcriptLabels = [
      '轉錄稿', '转录稿', '字幕記錄', '字幕记录',
      'transcript', 'Transcript', '文字起こし',
    ];

    let clicked = false;
    const buttons = document.querySelectorAll(
      '#description button, ytd-video-description-transcript-section-renderer button'
    );
    for (const btn of buttons) {
      const text = btn.textContent?.trim() || '';
      if (transcriptLabels.some((label) => text.includes(label))) {
        (btn as HTMLElement).click();
        clicked = true;
        break;
      }
    }

    if (!clicked) {
      // Collapse description back if we expanded it
      const collapseBtn = document.querySelector('#collapse') as HTMLElement;
      if (collapseBtn) collapseBtn.click();
      return [];
    }

    // Step 3: Wait for transcript segments to render
    await waitForElement('ytd-transcript-segment-renderer', 5000);
    await sleep(300); // Brief settle time

    // Step 4: Read segments
    const segments = readTranscriptSegmentsFromDOM();

    // Step 5: Close transcript panel silently
    const closeBtn = document.querySelector(
      'ytd-engagement-panel-section-list-renderer[target-id*="transcript"] #header button'
    ) as HTMLElement;
    if (closeBtn) closeBtn.click();

    // Also collapse description back
    await sleep(100);
    const collapseBtn = document.querySelector('#collapse') as HTMLElement;
    if (collapseBtn) collapseBtn.click();

    return segments;
  } catch (e) {
    console.error('[VideoLM] DOM transcript extraction failed', e);
    return [];
  }
}

/**
 * Read transcript segments from already-rendered DOM elements.
 */
function readTranscriptSegmentsFromDOM(): TranscriptSegment[] {
  const segmentEls = document.querySelectorAll('ytd-transcript-segment-renderer');
  const segments: TranscriptSegment[] = [];

  segmentEls.forEach((el) => {
    const timestamp = (
      el.querySelector('.segment-timestamp') as HTMLElement
    )?.textContent?.trim() || '';
    const text = (
      el.querySelector('.segment-text') as HTMLElement
    )?.textContent?.trim() || '';

    // Parse timestamp "0:42" or "1:23:45" to seconds
    const parts = timestamp.split(':').map(Number);
    let start = 0;
    if (parts.length === 3) start = parts[0] * 3600 + parts[1] * 60 + parts[2];
    else if (parts.length === 2) start = parts[0] * 60 + parts[1];

    if (text) {
      segments.push({ text, start, duration: 0 });
    }
  });

  return segments;
}

// ---------------------------------------------------------------------------
// 4. Full extraction pipeline (Tier 1 → Tier 2)
// ---------------------------------------------------------------------------

async function getVideoContent(): Promise<VideoContent | null> {
  const currentUrl = location.href;

  // Return cached if URL unchanged
  if (cachedContent && cachedUrl === currentUrl) {
    return cachedContent;
  }

  cachedUrl = currentUrl;
  cachedContent = null;

  try {
    const pr = extractPlayerResponseFromPage();
    if (!pr) return null;

    const meta = extractVideoMetadata(pr);
    const tracks = extractCaptionTracks(pr);
    const rawChapters = extractChapters(pr);

    // --- Two-tier transcript extraction ---
    // Tier 1: Silent timedtext fetch (fast, ms precision, may fail due to POT)
    let segments = await extractTranscriptTier1(pr);
    let extractionTier = 1;

    // Tier 2: Silent DOM scraping (reliable fallback)
    if (segments.length === 0 && tracks.length > 0) {
      segments = await extractTranscriptTier2();
      extractionTier = 2;
    }

    if (segments.length > 0) {
      console.log(`[VideoLM] Extracted ${segments.length} segments via Tier ${extractionTier}`);
    }

    // Assign segments to chapters
    const chapters: Chapter[] | undefined =
      rawChapters.length > 0
        ? rawChapters.map((ch) => ({
            ...ch,
            segments: segments.filter(
              (s) => s.start >= ch.startTime && s.start < ch.endTime,
            ),
          }))
        : undefined;

    const bestTrack = tracks.find((t) => !t.isAutoGenerated) ?? tracks[0];

    const content: VideoContent = {
      videoId: extractVideoId(currentUrl) ?? pr.videoDetails?.videoId ?? '',
      title: meta.title ?? '',
      author: meta.author ?? '',
      platform: 'youtube',
      transcript: segments,
      chapters,
      duration: meta.duration ?? 0,
      language: bestTrack?.languageCode || 'unknown',
      url: currentUrl,
      metadata: meta.metadata ?? { publishDate: '', viewCount: 0, tags: [] },
    };

    cachedContent = content;
    return content;
  } catch (e) {
    console.error('[VideoLM] Extraction failed', e);
    return null;
  }
}

// ---------------------------------------------------------------------------
// 5. Message listener
// ---------------------------------------------------------------------------

chrome.runtime.onMessage.addListener((message, _sender, sendResponse) => {
  if (message.type === 'PING') {
    sendResponse({ type: 'PONG' });
    return false;
  }

  if (message.type === 'GET_VIDEO_CONTENT') {
    getVideoContent()
      .then((content) => {
        sendResponse({ type: 'VIDEO_CONTENT', data: content });
      })
      .catch((err) => {
        sendResponse({
          type: 'VIDEO_CONTENT',
          data: null,
          error: `Extraction error: ${err instanceof Error ? err.message : String(err)}`,
        });
      });
    return true;
  }

  return false;
});

// ---------------------------------------------------------------------------
// 6. SPA navigation watcher
// ---------------------------------------------------------------------------

let lastUrl = location.href;

const observer = new MutationObserver(() => {
  if (location.href !== lastUrl) {
    lastUrl = location.href;
    cachedContent = null;
    cachedUrl = '';
  }
});
observer.observe(document.documentElement, { childList: true, subtree: true });

window.addEventListener('popstate', () => {
  cachedContent = null;
  cachedUrl = '';
});
